// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaddleThroughLychnidos.Infrastructure.Data.DataContext;

#nullable disable

namespace PaddleThroughLychnidos.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820175456_AddPassportStampsAndReviewUniqueness")]
    partial class AddPassportStampsAndReviewUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconUrl = "",
                            Name = "Jewelry"
                        },
                        new
                        {
                            Id = 2,
                            IconUrl = "",
                            Name = "TraditionalCostume"
                        },
                        new
                        {
                            Id = 3,
                            IconUrl = "",
                            Name = "WoodCarving"
                        },
                        new
                        {
                            Id = 4,
                            IconUrl = "",
                            Name = "HandmadePaper"
                        },
                        new
                        {
                            Id = 5,
                            IconUrl = "",
                            Name = "Iconography"
                        },
                        new
                        {
                            Id = 6,
                            IconUrl = "",
                            Name = "ArtGallery"
                        },
                        new
                        {
                            Id = 7,
                            IconUrl = "",
                            Name = "CraftWorkshopGeneral"
                        },
                        new
                        {
                            Id = 8,
                            IconUrl = "",
                            Name = "SouvenirShop"
                        });
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Itineraries", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.ItineraryStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItineraryId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("SuggestedTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ItineraryId", "Order")
                        .IsUnique();

                    b.ToTable("ItineraryStops", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.LearnVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RelatedCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("RelatedCategoryId");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique();

                    b.ToTable("LearnVideos", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("NewsItems", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.PassportStamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId", "ShopId")
                        .IsUnique();

                    b.ToTable("PassportStamps", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Products", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.ProductVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVideos", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolygonGeoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Varosh - Old Town of Ohrid - 6000 Ohrid, North Macedonia",
                            PolygonGeoJson = "{\"type\":\"Polygon\",\"coordinates\":[[[20.787599,41.114936],[20.788264,41.109979],[20.799301,41.111026],[20.800473,41.113924],[20.794001,41.116244],[20.789311,41.115731],[20.787599,41.114936]]]}"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Old Bazaar (Čaršija) - 6000 Ohrid, North Macedonia",
                            PolygonGeoJson = "{\"type\":\"Polygon\",\"coordinates\":[[[20.799199,41.112732],[20.800338,41.113574],[20.800338,41.113574],[20.802225,41.116929],[20.79801,41.116943],[20.799199,41.112732]]]}"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Plaošnik / Kaneo - 6000 Ohrid, North Macedonia",
                            PolygonGeoJson = "{\"type\":\"Polygon\",\"coordinates\":[[[20.791895,41.113603],[20.788127,41.113732],[20.78826,41.110899],[20.792445,41.11051],[20.792447,41.11052],[20.791895,41.113603]]]}"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "St. Naum Monastery - Ohrid Lake, North Macedonia",
                            PolygonGeoJson = "{\"type\":\"Polygon\",\"coordinates\":[[[20.732367,40.91161],[20.746379,40.908202],[20.74673,40.907989],[20.746769,40.907947],[20.760209,40.914992],[20.760223,40.914952],[20.745256,40.915788],[20.745323,40.915754],[20.732339,40.91165],[20.732367,40.91161]]]}"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Bay of Bones (Museum on Water) - Ohrid Lake, North Macedonia",
                            PolygonGeoJson = "{\"type\":\"Polygon\",\"coordinates\":[[[20.800361,40.993928],[20.801592,40.996752],[20.801571,40.996706],[20.801584,40.996697],[20.796341,40.996917],[20.796344,40.996909],[20.796153,40.993998],[20.796163,40.99399],[20.800359,40.993935],[20.800361,40.993928]]]}"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Ohrid Lakefront Promenade - 6000 Ohrid, North Macedonia",
                            PolygonGeoJson = "{\"type\":\"Polygon\",\"coordinates\":[[[20.735171,40.914576],[20.777828,40.912398],[20.777252,40.911744],[20.777375,40.911598],[20.84729,41.030999],[20.847329,41.030958],[20.802615,41.106184],[20.80274,41.105997],[20.735171,40.914576]]]}"
                        });
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId", "ShopId")
                        .IsUnique();

                    b.ToTable("Reviews", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstagramHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StructuredHoursJson")
                        .HasColumnType("text");

                    b.Property<int?>("UserRatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.Property<string>("WhatsappNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RegionId");

                    b.ToTable("Shops", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.ShopImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopImages", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.TravelPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ItineraryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("TravelPlanItems", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Itinerary", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.ItineraryStop", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Itinerary", "Itinerary")
                        .WithMany("Stops")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Shop", "Shop")
                        .WithMany("ItineraryStops")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Itinerary");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.LearnVideo", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Category", "RelatedCategory")
                        .WithMany()
                        .HasForeignKey("RelatedCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedCategory");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.PassportStamp", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Product", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.ProductVideo", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Product", "Product")
                        .WithMany("Videos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Review", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Shop", "Shop")
                        .WithMany("Reviews")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Shop", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Category", "Category")
                        .WithMany("Shops")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.User", "Owner")
                        .WithMany("Shops")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Region", "Region")
                        .WithMany("Shops")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Owner");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.ShopImage", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Shop", "Shop")
                        .WithMany("Images")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.TravelPlanItem", b =>
                {
                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Itinerary", "Itinerary")
                        .WithMany()
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaddleThroughLychnidos.Domain.Entities.User", "User")
                        .WithMany("TravelPlan")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerary");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Category", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Itinerary", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Product", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Region", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.Shop", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ItineraryStops");

                    b.Navigation("Products");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PaddleThroughLychnidos.Domain.Entities.User", b =>
                {
                    b.Navigation("Shops");

                    b.Navigation("TravelPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
