<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\Downloads\drive-download-20260814T135735Z-1-001\bay.json" Link="Data\DataContext\SeedData\regions\bay.json" />
    <Content Include="..\..\..\..\Downloads\drive-download-20260814T135735Z-1-001\carsija.json" Link="Data\DataContext\SeedData\regions\carsija.json" />
    <Content Include="..\..\..\..\Downloads\drive-download-20260814T135735Z-1-001\krajbrezje.json" Link="Data\DataContext\SeedData\regions\krajbrezje.json" />
    <Content Include="..\..\..\..\Downloads\drive-download-20260814T135735Z-1-001\plaosnik.json" Link="Data\DataContext\SeedData\regions\plaosnik.json" />
    <Content Include="..\..\..\..\Downloads\drive-download-20260814T135735Z-1-001\sv naum.json" Link="Data\DataContext\SeedData\regions\sv naum.json" />
    <Content Include="..\..\..\..\Downloads\drive-download-20260814T135735Z-1-001\varosh.json" Link="Data\DataContext\SeedData\regions\varosh.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
    <Folder Include="Data\DataContext\SeedData\regions\" />
    <Folder Include="Migrations\" />
    <Folder Include="DependencyInjection\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaddleThroughLychnidos.Domain\PaddleThroughLychnidos.Domain.csproj" />
    <ProjectReference Include="..\PaddleThroughLychnidos.Application\PaddleThroughLychnidos.Application.csproj" />
  </ItemGroup>

</Project>
